### ISSUE TITLE
Keyboard input failing when executing scripts???

### ISSUE THREAD

**Issue by brunofavs** [brunofavs/my_arch_issues#10]
`rosrun atom_calibration calibrate -json $ATOM_DATASETS/softbot/dataset_perfect_simulation/dataset_corrected.json -v  -ntfv 1 1 -ntfl "world:base_footpri"`

```
Traceback (most recent call last):
  File "/home/bruno/atom_ws/devel/lib/atom_calibration/calibrate", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/bruno/atom_ws/src/atom/atom_calibration/scripts/calibrate", line 25, in <module>
    from atom_calibration.calibration.objective_function import errorReport, objectiveFunction
  File "/home/bruno/atom_ws/src/atom/atom_calibration/src/atom_calibration/calibration/objective_function.py", line 16, in <module>
    from atom_core.joint_models import getTransformationFromJoint
  File "/home/bruno/atom_ws/src/atom/atom_core/src/atom_core/joint_models.py", line 7, in <module>
    from atom_core.utilities import atomError
  File "/home/bruno/atom_ws/src/atom/atom_core/src/atom_core/utilities.py", line 25, in <module>
    from pynput import keyboard
  File "/usr/local/lib/python3.8/dist-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/usr/local/lib/python3.8/dist-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/usr/local/lib/python3.8/dist-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":0": b\'Authorization required, but no authorization protocol specified\\n\'', DisplayConnectionError(':0', b'Authorization required, but no authorization protocol specified\n'))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
```

This was supposed to just print a error, nothing more.

**Comment by brunofavs** [comment]
https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#resolve-error-cannot-open-display-0

This solved it
